export const HTTP_HEADERS = {
    CONTENT_TYPE: "content-type",
    CONTENT_LENGTH: "content-length",
    CONTENT_ENCODING: "content-encoding",
    CONTENT_RANGE: "content-range",
    CACHE_CONTROL: "cache-control",
    ETAG: "etag",
    IF_NONE_MATCH: "if-none-match",
    IF_MODIFIED_SINCE: "if-modified-since",
    LAST_MODIFIED: "last-modified",
    EXPIRES: "expires",
    PRAGMA: "pragma",
    VARY: "vary",
    ACCESS_CONTROL_ALLOW_ORIGIN: "access-control-allow-origin",
    ACCESS_CONTROL_ALLOW_CREDENTIALS: "access-control-allow-credentials",
    ACCESS_CONTROL_ALLOW_METHODS: "access-control-allow-methods",
    ACCESS_CONTROL_ALLOW_HEADERS: "access-control-allow-headers",
    ACCESS_CONTROL_EXPOSE_HEADERS: "access-control-expose-headers",
    ACCESS_CONTROL_MAX_AGE: "access-control-max-age",
    X_CONTENT_TYPE_OPTIONS: "x-content-type-options",
    X_FRAME_OPTIONS: "x-frame-options",
    X_XSS_PROTECTION: "x-xss-protection",
    STRICT_TRANSPORT_SECURITY: "strict-transport-security",
    REFERRER_POLICY: "referrer-policy",
    CONTENT_SECURITY_POLICY: "content-security-policy",
    AUTHORIZATION: "authorization",
    WWW_AUTHENTICATE: "www-authenticate",
    SET_COOKIE: "set-cookie",
    COOKIE: "cookie",
    LOCATION: "location",
    REFRESH: "refresh",
    ACCEPT_RANGES: "accept-ranges",
    RANGE: "range",
    CONNECTION: "connection",
    KEEP_ALIVE: "keep-alive",
    TRANSFER_ENCODING: "transfer-encoding",
    X_ACCEL_BUFFERING: "x-accel-buffering",
    X_RATELIMIT_LIMIT: "x-ratelimit-limit",
    X_RATELIMIT_REMAINING: "x-ratelimit-remaining",
    X_RATELIMIT_RESET: "x-ratelimit-reset",
    RETRY_AFTER: "retry-after",
    X_REQUEST_ID: "x-request-id",
    HOST: "host",
    USER_AGENT: "user-agent",
    REFERER: "referer",
    ORIGIN: "origin",
    ACCEPT: "accept",
    ACCEPT_ENCODING: "accept-encoding",
    ACCEPT_LANGUAGE: "accept-language",
    DATE: "date",
} as const

export type HeaderName = (typeof HTTP_HEADERS)[keyof typeof HTTP_HEADERS] | (string & {})

export const CONTENT_TYPES = {
    TEXT_PLAIN: "text/plain; charset=UTF-8",
    TEXT_HTML: "text/html; charset=UTF-8",
    TEXT_CSS: "text/css; charset=UTF-8",
    TEXT_JAVASCRIPT: "text/javascript; charset=UTF-8",
    TEXT_CSV: "text/csv; charset=UTF-8",
    TEXT_EVENT_STREAM: "text/event-stream",
    APPLICATION_JSON: "application/json",
    APPLICATION_JSON_UTF8: "application/json; charset=UTF-8",
    APPLICATION_OCTET_STREAM: "application/octet-stream",
    APPLICATION_PDF: "application/pdf",
    APPLICATION_WASM: "application/wasm",
    APPLICATION_XML: "application/xml",
    TEXT_XML: "text/xml",
    APPLICATION_X_WWW_FORM_URLENCODED: "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA: "multipart/form-data",
    APPLICATION_VND_APPLE_MPEGURL: "application/vnd.apple.mpegurl",
    APPLICATION_X_MPEGURL: "application/x-mpegurl",
    AUDIO_MPEG: "audio/mpeg",
    AUDIO_OGG: "audio/ogg",
    AUDIO_WAV: "audio/wav",
    VIDEO_MP4: "video/mp4",
    VIDEO_WEBM: "video/webm",
    IMAGE_PNG: "image/png",
    IMAGE_JPEG: "image/jpeg",
    IMAGE_GIF: "image/gif",
    IMAGE_SVG_XML: "image/svg+xml",
    IMAGE_WEBP: "image/webp",
    IMAGE_ICO: "image/x-icon",
    FONT_WOFF: "font/woff",
    FONT_WOFF2: "font/woff2",
    FONT_TTF: "font/ttf",
    APPLICATION_ZIP: "application/zip",
    APPLICATION_GZIP: "application/gzip",
} as const

export type ContentType = (typeof CONTENT_TYPES)[keyof typeof CONTENT_TYPES] | (string & {})

export const CACHE_CONTROL = {
    NO_CACHE: "no-cache",
    NO_STORE: "no-store",
    MUST_REVALIDATE: "must-revalidate",
    PUBLIC_MAX_AGE_0: "public, max-age=0",
    PUBLIC_MAX_AGE_60: "public, max-age=60",
    PUBLIC_MAX_AGE_300: "public, max-age=300",
    PUBLIC_MAX_AGE_3600: "public, max-age=3600",
    PUBLIC_MAX_AGE_86400: "public, max-age=86400",
    PUBLIC_IMMUTABLE: "public, max-age=31536000, immutable",
    PRIVATE_NO_CACHE: "private, no-cache",
    PRIVATE_MAX_AGE_0: "private, max-age=0",
} as const

export type CacheControlValue = (typeof CACHE_CONTROL)[keyof typeof CACHE_CONTROL] | (string & {})

export const SECURITY_HEADERS = {
    NOSNIFF: "nosniff",
    DENY: "DENY",
    SAMEORIGIN: "SAMEORIGIN",
    ALLOW_FROM: "ALLOW-FROM",
    MODE_DENY: "mode=block",
    ONE: "1; mode=block",
} as const
